module.exports = function(config) {
    config.set({
        basePath:'.',
        frameworks:['jasmine'],
        files:[
            {pattern:'bower_components/angular/angular.js'},
            {pattern:'bower_components/angular-mocks/angular-mocks.js'},
            {pattern:'bower_components/thk-cache-control-mock/src/cache.control.mock.js'},
            {pattern:'bower_components/thk-notifications-mock/src/notifications.mock.js'},
            {pattern:'bower_components/thk-config-mock/src/config.mock.js'},
            {pattern:'bower_components/thinkerit.angularx.bootstrap.mocks/src/angularx.bootstrap.mocks.js'},
            {pattern:'bower_components/binarta.toggle.edit.mode.angular/src/main/js/toggle.edit.mode.js'},
            {pattern:'src/main/js/image.in.memory.js'},
            {pattern:'src/main/js/image.rest.js'},
            {pattern:'src/main/js/images.js'},
            {pattern:'src/test/js/**/*.js'}
        ],
        browsers:['PhantomJS']
    });
};